#----------------------------------------------------------------------
# $Id$
#
# Takes the filter-diffs.YYYYMMDDHHMMSS file generated by the
# compare-filters.py script and use it (piped to this script)
# and creates a Windows shell script for installing all of the
# changed filters in a sandbox. You'll probably need to edit
# the script before running it (for example, UpdateFilter.py
# isn't where this script assumes it is, or you want a more
# specific, informative comment (as you should) or you want
# to replace %2 with "" - as you would on QA or DEV when running
# directly on the server), but that should be very simple search
# and replace in a decent editor.
#----------------------------------------------------------------------
import sys

print "@if [%2] == [] goto usage"
for line in sys.stdin:
    filename = line.strip()
    print(r"python ..\DevTools\Utilities\UpdateFilter.py -v Y -p Y "
          "-c \"scripted filter update\" %%1 %%2 %s" % filename)
print "@goto done"
print ":usage"
print "@echo must specify user-id and password"
print ":done"
